# Add configuration values here, as shown below.
#
 FOG_DIRECTORY: 'this-is-the-stuff-24'
 AWS_ACCESS_KEY_ID: 'AKIAQ3XBVD4E6E4H7BAG'
 AWS_SECRET_ACCESS_KEY: '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'
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
